- README.md
- molecule/default/playbook.yml
- templates/reboot-notify.sh.j2
Test -e (exists) not -x (executable). Use root@localhost to get the correct from
address mapping.
> Fix reboot-notify

- .circleci/config.yml
- tasks/main.yml
This prevents us from alerting on services that haven't been provisioned yet.
> Move New Relic to the end of the role

- tasks/main.yml
Fixes https://github.com/GSA/datagov-deploy-common/issues/17
include* is used for dynamic operation and import* is
used for static operation. Based on the behavior described[1], we want the
static operation so that tags and when statements are "copied" to all imported
tasks/roles. We're not using any dynamic functionality here.
[1]: https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse.html#differences-between-static-and-dynamic
> Use import_* instead of include_*

- tasks/nessus.yml
Fixes #16
Fix the syntax for the registered result test. nessus registration fails if
already registered. If the agent is not registered, the command fails, so that
is when the nessus registration step should be applied.
> [nessus] fix nessus on first registration

- vars/bionic.yml
- vars/xenial.yml
This allows python to build optional modules like openssl, zlib, bzip, etc, which are required for ckan deps.
> Add missing python build dependencies

- vars/bionic.yml
- vars/trusty.yml
- vars/xenial.yml
Originally the plan was to replace supervisor with systemd service files for any
platform services. We haven't done that work yet, so keep supervisor installed
on these hosts for now.
> Add supervisor to systemd hosts

- tasks/main.yml
Fixes error:
```
/etc/cron.daily/logrotate:
error: upstart:7 unknown user 'upstart'
error: found error in /var/log/upstart/*.log , skipping
```
> [upstart] fix broken logrotate

- Pipfile.lock
- README.md
- molecule/default/molecule.yml
- molecule/default/playbook.yml
- molecule/default/prepare.yml
- molecule/default/tests/test_default.py
- tasks/main.yml
This adds operator SSH keys to access all the hosts (through the jumpbox) and allows operators to use SSH agent forwarding to accomplish this. This eliminates the need for operators to use the "root" ssh key from the ubuntu user on jumpbox.
We're moving toward a model where operator access is used for debugging, and deployment will be automated.
> Add Operator access via SSH

- README.md
- defaults/main.yml
- files/audit-report.sh
- files/etc_logwatch_conf_ignore.conf
- molecule/default/tests/test_default.py
- tasks/audit-report.yml
- tasks/main.yml
https://github.com/GSA/datagov-deploy/issues/1093
This adds a custom script to be run weekly in order to meet the AU-6 audit
control. The script includes aureport for parsing auditd logs, and logwatch for
other system logs. I've also included an ignore file for logwatch, so that we
can filter out known good log lines.
The intent is to record what is _normal_ for our system as
configuration-as-code. The system will highlight anything that is not
considered normal for human investigation and follow up.
> Automated audit report

- Pipfile
- Pipfile.lock
- molecule/default/molecule.yml
Also bumps Ansible to 2.7 which is required by pytest-xdist.
I'm hoping to imporove the CI timeouts we're seeing.
> Use pytest-xdist for parallel CI tests

- .circleci/config.yml
- files/audit-report.sh
- molecule/default/tests/test_default.py
- tasks/audit-report.yml
- Use full paths to sbin within cron.
- Selectively run aureport on trusty, which does not support all options.
- Update the cron for timezones, run on Friday mornings
- Add the hostname to the footer
> [audit-report] fixes

- .circleci/config.yml
- files/audit-report.sh
- molecule/default/tests/test_default.py
The test hanging was the same reason why we're not seeing any data in the report. aureport is reading from stdin when used non-interactively. Specify the input logs from configuration and restore the test.
> [audit-report] fix data appearing from aureport

- README.md
- tasks/trendmicro.yml
https://github.com/GSA/datagov-deploy/issues/1389
As the comment mentioned, this creates removes the hard dependency of having
these inventory groups. We ran into this again when removing crm-web. This makes
it explicit that trendmicro_policy_id should be set.
> [trendmicro] remove inventory groups

- tasks/trendmicro.yml
https://github.com/GSA/datagov-deploy/issues/1389
All hosts in a trendmicro environment should have a policy set. Confirmed with
SecOps.
> [trendmicro] assert policy id is set

- defaults/main.yml
https://github.com/GSA/datagov-deploy-common/issues/24
Always pull in the latest version with the latest fixes and security updates.
> [filebeat] don't pin version in apt

- defaults/main.yml
- tasks/main.yml
https://github.com/GSA/datagov-deploy-common/issues/24
Right, default variables only apply to the role, so they won't be applied to the third-party jobscore.beats role. Apply the version specifier at the import task.
> [filebeat] version specifier for filebeat

- tasks/ua.yml
/etc/ubuntu-advantage exists once ua is installed, but the data directory,
/var/lib/ubuntu-advantage is only populated after subscription.
> Fix path for ua subscription

- tasks/trendmicro.yml
https://github.com/GSA/datagov-deploy/issues/1825
Seeing a hang on the registration task after installing trend on a new instance.
Registration output shows 30 retries at 30 seconds each, which is too long to
wait. The GSA Firewall team says partial registration can happen on occasion and
may require a manual fix on their end. Add a timeout and actionable debug
message when this happens.
Presumably the 10 second sleep was added due to some kind of hang or hiccup
while trendmicro is starting up immediately after install. Use `retries` and
`delay` instead to achieve better robustness without an unnecessary sleep.
> [trendmicro] "fix" hang during registration

- molecule/default/tests/test_default.py
- tasks/tls.yml
part of https://github.com/GSA/datagov-deploy/issues/1855
Command `update-ca-certificates` is not updating `/etc/ssl/certs/ca-certificates.crt` after change https://github.com/GSA/datagov-deploy/pull/1856. It turns out `/etc/ssl/certs/` only works for new cert file. To let existing cert get picked up by `update-ca-certificates`, it needs be put in directory `/usr/local/share/ca-certificates/`.
> add symlink of host certificate

- README.md
- defaults/main.yml
- molecule/default/playbook.yml
- molecule/default/prepare.yml
- molecule/default/tests/test_default.py
- molecule/ua/tests/test_default.py
- tasks/main.yml
- Remove `active` functionality for common_operators list, and manage ssh key creation as a block per [this change](https://github.com/GSA/datagov-deploy/issues/1837)
- Add `from` clause for authorized_keys file so [access can be limited](https://github.com/GSA/datagov-deploy/issues/1203)
**Note: Will require cleanup once run on all systems.**
> Initial common operators removal fix

- README.md
- tasks/python-upgrade.yml
- vars/bionic.yml
- vars/trusty.yml
https://github.com/GSA/datagov-ckan-multi/issues/359
In pysaml 4.9.0, python with dbm (gdbm) support is necessary. Make sure it's installed and a flag exists to force a python rebuild.
> Rebuild python with gdbm support for pysaml2 in CKAN

- .circleci/config.yml
- Pipfile
- tasks/main.yml
https://github.com/GSA/datagov-deploy/issues/2103
"Fix" variable collision by setting it to the default. This let's us update to v3.1.6.
> [postfix] force variable allowing update of postfix role

- tasks/main.yml
This was discused as part of an Incident retro, but I can't find the issue.
This allows us to specify a custom shell prompt, so can remind operators they
are on production instances and avoid commands getting run in the wrong shell
window.
> [common] allow for custom shell prompt

- tasks/hardening.yml
- tasks/main.yml
https://github.com/GSA/datagov-deploy/issues/2655
Avoid role failing when the ipv6 subsystem is disabled.
> [hardening] fix ipv6 sysctl configuration
